version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - '5672:5672'
      - '15672:15672'

  api:
    build: .
    container_name: youapp-api
    restart: unless-stopped
    depends_on:
      - mongo
      - rabbitmq
    environment:
      MONGO_URI: mongodb://mongo:27017/youapp
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
      JWT_SECRET: supersecret
    ports:
      - '3000:3000'

volumes:
  mongo-data:
